version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: dotnet restore
after_build:
- ps: dotnet pack -c release
build:
  verbosity: minimal
test_script:
- ps: dotnet test .\RxSockets.Tests\RxSockets.Tests.csproj
artifacts:
- path: '**\*.nupkg'
